# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQKDWnfOMVpLfGUyvfqA0aQf0gnvxNML
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

data = pd.read_csv('''./Data/spine.csv''')

x = np.array(data[['Col1','Col2','Col3','Col4','Col5','Col6','Col7','Col8','Col9','Col10','Col11','Col12']])
y = data[['Class_label']]


xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

model = Sequential()
model.add(Dense(12, input_dim=12, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(xtrain, ytrain, epochs=100, batch_size=50)

model.evaluate(xtest, ytest)

y_pred = model.predict(xtest)
y_pred = (y_pred > 0.5)
matrix = confusion_matrix(ytest, y_pred)
plt.matshow(matrix)
plt.colorbar()
plt.show()